from __future__ import annotations

from enum import StrEnum


class TraceErrorCode(StrEnum):
    ARTIFACT_DIGEST_MISMATCH = "ARTIFACT_DIGEST_MISMATCH"
    ARTIFACT_CONTENT_MISSING = "ARTIFACT_CONTENT_MISSING"
    ARTIFACT_SCHEMA_UNSUPPORTED = "ARTIFACT_SCHEMA_UNSUPPORTED"
    ARTIFACT_PRODUCER_UNBOUND = "ARTIFACT_PRODUCER_UNBOUND"
    ARTIFACT_LINEAGE_INVALID = "ARTIFACT_LINEAGE_INVALID"
    STAGE_OUTPUT_INVALID = "STAGE_OUTPUT_INVALID"
    STAGE_TRANSITION_INVALID = "STAGE_TRANSITION_INVALID"
    RUN_TRANSITION_INVALID = "RUN_TRANSITION_INVALID"
    PLAN_SNAPSHOT_INVALID = "PLAN_SNAPSHOT_INVALID"
    PLAN_IMPLEMENTATION_DRIFT = "PLAN_IMPLEMENTATION_DRIFT"
    TRACE_STORAGE_FAILURE = "TRACE_STORAGE_FAILURE"
    PLUGIN_NOT_REGISTERED = "PLUGIN_NOT_REGISTERED"
    PLUGIN_UNAVAILABLE = "PLUGIN_UNAVAILABLE"
    PLUGIN_INVOCATION_TIMEOUT = "PLUGIN_INVOCATION_TIMEOUT"
    PLUGIN_INVOCATION_CANCELLED = "PLUGIN_INVOCATION_CANCELLED"
    PLUGIN_CRASHED = "PLUGIN_CRASHED"
    PLUGIN_RESULT_INVALID = "PLUGIN_RESULT_INVALID"
    PLUGIN_OUTPUT_LIMIT_EXCEEDED = "PLUGIN_OUTPUT_LIMIT_EXCEEDED"
    CANONICAL_INPUT_INVALID = "CANONICAL_INPUT_INVALID"
    CANONICAL_DOCUMENT_INVALID = "CANONICAL_DOCUMENT_INVALID"
    CANONICAL_FIELD_UNBOUNDED = "CANONICAL_FIELD_UNBOUNDED"
    EMBEDDING_DIMENSION_MISMATCH = "EMBEDDING_DIMENSION_MISMATCH"
    EMBEDDING_RECORD_INVALID = "EMBEDDING_RECORD_INVALID"
    INDEX_INPUT_INVALID = "INDEX_INPUT_INVALID"
    INDEX_SEGMENT_LOCKED = "INDEX_SEGMENT_LOCKED"
    RETRIEVAL_INPUT_INVALID = "RETRIEVAL_INPUT_INVALID"
    RETRIEVAL_CANDIDATE_INVALID = "RETRIEVAL_CANDIDATE_INVALID"
    RETRIEVAL_INDEX_IDENTITY_STALE = "RETRIEVAL_INDEX_IDENTITY_STALE"
    FUSION_INPUT_INVALID = "FUSION_INPUT_INVALID"
    FUSION_CANDIDATE_INVALID = "FUSION_CANDIDATE_INVALID"
    RERANK_INPUT_INVALID = "RERANK_INPUT_INVALID"
    RERANK_CANDIDATE_INVALID = "RERANK_CANDIDATE_INVALID"
    CONTEXT_INPUT_INVALID = "CONTEXT_INPUT_INVALID"
    CONTEXT_CANDIDATE_INVALID = "CONTEXT_CANDIDATE_INVALID"
    GENERATION_INPUT_INVALID = "GENERATION_INPUT_INVALID"
    GENERATION_UNAVAILABLE = "GENERATION_UNAVAILABLE"
    GENERATION_PROVIDER_FAILED = "GENERATION_PROVIDER_FAILED"
    VERIFICATION_INPUT_INVALID = "VERIFICATION_INPUT_INVALID"


class TraceError(RuntimeError):
    """An actionable, public-safe domain failure."""

    def __init__(self, code: TraceErrorCode) -> None:
        super().__init__(code.value)
        self.code = code
