from __future__ import annotations

from enum import StrEnum


class PluginErrorCode(StrEnum):
    DESCRIPTOR_INVALID = "PLUGIN_DESCRIPTOR_INVALID"
    ID_DUPLICATE = "PLUGIN_ID_DUPLICATE"
    RUNNER_UNSUPPORTED = "PLUGIN_RUNNER_UNSUPPORTED"
    SCHEMA_INCOMPATIBLE = "PLUGIN_SCHEMA_INCOMPATIBLE"
    EXECUTABLE_CONFIGURATION_FORBIDDEN = "PLUGIN_EXECUTABLE_CONFIGURATION_FORBIDDEN"
    NOT_REGISTERED = "PLUGIN_NOT_REGISTERED"
    UNAVAILABLE = "PLUGIN_UNAVAILABLE"
    TIMEOUT = "PLUGIN_INVOCATION_TIMEOUT"
    CANCELLED = "PLUGIN_INVOCATION_CANCELLED"
    CRASHED = "PLUGIN_CRASHED"
    RESULT_INVALID = "PLUGIN_RESULT_INVALID"
    OUTPUT_LIMIT_EXCEEDED = "PLUGIN_OUTPUT_LIMIT_EXCEEDED"
    CANONICAL_INPUT_INVALID = "CANONICAL_INPUT_INVALID"
    CANONICAL_DOCUMENT_INVALID = "CANONICAL_DOCUMENT_INVALID"
    CANONICAL_FIELD_UNBOUNDED = "CANONICAL_FIELD_UNBOUNDED"


class PluginError(RuntimeError):
    def __init__(self, code: PluginErrorCode) -> None:
        super().__init__(code.value)
        self.code = code
