from enum import StrEnum


class QueryProfileErrorCode(StrEnum):
    PARSE_INVALID = "QUERY_PROFILE_PARSE_INVALID"
    UNSAFE_CONTENT = "QUERY_PROFILE_UNSAFE_CONTENT"
    PLUGIN_UNKNOWN = "QUERY_PROFILE_PLUGIN_UNKNOWN"
    PLUGIN_UNAVAILABLE = "QUERY_PROFILE_PLUGIN_UNAVAILABLE"
    CONFIGURATION_INVALID = "QUERY_PROFILE_CONFIGURATION_INVALID"
    PORT_UNBOUND = "QUERY_PROFILE_PORT_UNBOUND"
    SCHEMA_INCOMPATIBLE = "QUERY_PROFILE_SCHEMA_INCOMPATIBLE"
    STAGE_ORDER_INVALID = "QUERY_PROFILE_STAGE_ORDER_INVALID"
    GRAPH_CYCLE = "QUERY_PROFILE_GRAPH_CYCLE"
    CONDITION_UNSUPPORTED = "QUERY_PROFILE_CONDITION_UNSUPPORTED"
    FINAL_VALIDATION_MISSING = "QUERY_PROFILE_FINAL_VALIDATION_MISSING"
    REPAIR_UNBOUNDED = "QUERY_PROFILE_REPAIR_UNBOUNDED"
    SELECTION_INVALID = "QUERY_PROFILE_SELECTION_INVALID"


class QueryProfileError(ValueError):
    def __init__(self, code: QueryProfileErrorCode, location: str = "/") -> None:
        self.code, self.location = code, location[:256]
        super().__init__(f"{code.value} at {self.location}")
